<?php

return [
    [
        "id" => 1,
        "title" => "Appartamento al Centro Storico",
        "description" => "Accogliente appartamento nel cuore della città, vicino a tutti i servizi.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 80,
        "address" => "Via Roma 1, Roma",
        "lat" => "41.93003",
        "long" => "12.45531",
        "image" => "https://trovacasacomo.it/preview/5936/imm_3303-1200-800.jpg"
    ],
    [
        "id" => 2,
        "title" => "Villetta con Giardino",
        "description" => "Spaziosa villetta immersa nel verde con giardino privato.",
        "beds" => 4,
        "bathrooms" => 2,
        "rooms" => 5,
        "mq" => 150,
        "address" => "Via dei Giardini 10, Milano",
        "lat" => "45.45471",
        "long" => "9.1325",
        "image" => "https://www.casavacanzeaffitti.it/wp-content/uploads/2021/02/IMG_3366.jpg"
    ],
    [
        "id" => 3,
        "title" => "Attico Vista Mare",
        "description" => "Luminoso attico con splendida vista sul mare.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 120,
        "address" => "Via del Mare 5, Napoli",
        "lat" => "40.851798",
        "long" => "14.268120",
        "image" => "https://www.hotelmeeting.com/wp-content/uploads/2021/07/5038.jpg"
    ],
    [
        "id" => 4,
        "title" => "Appartamento Moderno",
        "description" => "Appartamento completamente ristrutturato in stile moderno.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 90,
        "address" => "Via Garibaldi 15, Torino",
        "lat" => "45.070312",
        "long" => "7.686856",
        "image" => "https://www.startpreventivi.it/wp-content/themes/Avada-Child-Theme/images/Blog/Case-Appartamenti/Appartamento-moderno-elegante/5-appartamento-moderno-elegante.jpg"
    ],
    [
        "id" => 5,
        "title" => "Casa Vacanze sul Lago",
        "description" => "Casa vacanze con accesso diretto al lago e vista panoramica.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 100,
        "lat" => "45.808059",
        "long" => "9.085176",
        "address" => "Via Lungolago 20, Como",
        "image" => "https://blog.casa.it/wp-content/uploads/2014/06/casa_al_lago6.jpg"
    ],
    [
        "id" => 6,
        "title" => "Appartamento in Zona Universitaria",
        "description" => "Perfetto per studenti, a pochi passi dall'università.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 60,
        "lat" => "44.494887",
        "long" => "11.342616",
        "address" => "Via Zamboni 33, Bologna",
        "image" => "https://www.leresidenzedelcampus.it/wp-content/uploads/2016/03/affitto-appartamenti-parma.jpg"
    ],
    [
        "id" => 7,
        "title" => "Appartamento in Villa d'Epoca",
        "description" => "Splendido appartamento in villa d'epoca, immerso nel verde.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 130,
        "address" => "Via Verdi 5, Firenze",
        "lat" => "43.769562",
        "long" => "11.255814",
        "image" => "https://trepievi.com/wp-content/uploads/2021/09/Esterni-Appartamenti-Menaggio-Rif.MA023H-14_rid.jpg"
    ],
    [
        "id" => 8,
        "title" => "Monolocale Arredato",
        "description" => "Monolocale completamente arredato in zona centrale.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 40,
        "address" => "Corso Umberto I 10, Bari",
        "lat" => "41.117143",
        "long" => "16.871871",
        "image" => "https://mondodesign.it/wp-content/uploads/2016/07/Arredare-Monolocale-86.jpg"
    ],
    [
        "id" => 9,
        "title" => "Trilocale con Vista",
        "description" => "Appartamento trilocale con vista mozzafiato sulla città.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 85,
        "address" => "Via Toledo 12, Napoli",
        "lat" => "40.851798",
        "long" => "14.268120",
        "image" => "https://it.gardalive.com/var/21925/storage/images/media/immagini/ufficio-manerba/man200/man200-3/614941-1-ita-IT/man200-3_full25.jpg"
    ],
    [
        "id" => 11,
        "title" => "Appartamento con Terrazzo Panoramico",
        "description" => "Splendido appartamento con terrazzo panoramico e vista sulla città.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 85,
        "address" => "Via delle Rose 10, Verona",
        "lat" => "45.429809",
        "long" => "10.991028",
        "image" => "https://www.apartments.com/blog/sites/default/files/styles/x_large/public/image/2023-06/apartment-kitchen.jpg.webp?itok=bd9ds5dP.jpg"
    ],
    [
        "id" => 13,
        "title" => "Bilocale Moderno e Luminoso",
        "description" => "Bilocale moderno e luminoso, con arredamento contemporaneo e ampi spazi.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 70,
        "address" => "Corso Vittorio Emanuele 5, Roma",
        "lat" => "41.93003",
        "long" => "12.45531",
        "image" => "http://t3.gstatic.com/licensed-image?q=tbn:ANd9GcQeJfyZcjphYfbpv7Igoo-5DxaHmgM-xcZP7xrwJxl9kEz43lkW9G-nO72fx5XE7L8FMzdBBGSi1QYNKGpsDfE"
    ],
    [
        "id" => 14,
        "title" => "Casa Storica con Giardino",
        "description" => "Affascinante casa storica con ampio giardino privato e dettagli d'epoca.",
        "beds" => 4,
        "bathrooms" => 3,
        "rooms" => 6,
        "mq" => 200,
        "address" => "Via delle Magnolie 12, Firenze",
        "lat" => "43.769562",
        "long" => "11.255814",
        "image" => "http://t3.gstatic.com/licensed-image?q=tbn:ANd9GcSn2awRHLyko5FDK9or4yETdWyncxT99VC3g1MuuaWn3MMm2RGi9dw7YmMY20eF1m8eHkKh3MFYzfZOvIRKfJs"
    ],
    [
        "id" => 15,
        "title" => "Appartamento in Loft Ristrutturato",
        "description" => "Spazioso loft ristrutturato con elementi industriali e ampie finestre.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 100,
        "address" => "Via Industriale 25, Torino",
        "lat" => "45.070312",
        "long" => "7.686856",
        "image" => "http://t1.gstatic.com/licensed-image?q=tbn:ANd9GcTxJZTmS7GL78r5FPdolbpBxPaSYvl_xd3Es1yGz5lTqyK1fDbiycZ320YUpEPLGyyHaHbj4tscInBMpClLhYw"
    ],
    [
        "id" => 16,
        "title" => "Appartamento con Piscina Privata",
        "description" => "Lussuoso appartamento con piscina privata e giardino.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 140,
        "address" => "Via dei Fiori 8, Genova",
        "lat" => "44.405650",
        "long" => "8.946256",
        "image" => "https://www.grubbproperties.com/sites/default/files/blog/intelligent-building-design-1536x1024_0.jpg"
    ],
    [
        "id" => 17,
        "title" => "Monolocale in Zona Universitaria",
        "description" => "Accogliente monolocale ideale per studenti, vicino all'università.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 45,
        "address" => "Via Università 15, Pompei",
        "lat" => "40.748804",
        "long" => "14.498138",
        "image" => "https://www.grubbproperties.com/sites/default/files/images/intelligent-construction-1024x684.jpg"
    ],
    [
        "id" => 18,
        "title" => "Appartamento con Vista sul Mare",
        "description" => "Meraviglioso appartamento con vista mozzafiato sul mare e terrazzo privato.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 130,
        "address" => "Lungomare 20, Napoli",
        "lat" => "40.851798",
        "long" => "14.268120",
        "image" => "https://www.grubbproperties.com/sites/default/files/images/lam_pool-1024x683.jpg"
    ],
    [
        "id" => 19,
        "title" => "Casa in Campagna",
        "description" => "Rinomata casa in campagna con ampio terreno e privacy.",
        "beds" => 5,
        "bathrooms" => 3,
        "rooms" => 7,
        "mq" => 250,
        "address" => "Strada delle Campagne 22, Siena",
        "lat" => "43.318000",
        "long" => "11.330000",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/link%20mint%20st_exterior%201.png"
    ],
    [
        "id" => 20,
        "title" => "Appartamento Centrale con Garage",
        "description" => "Comodo appartamento centrale con garage privato e vista sulla città.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 80,
        "address" => "Via Centrale 30, Trieste",
        "lat" => "45.649527",
        "long" => "13.767834",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/link%20mint%20st_exterior%202.png"
    ],
    [
        "id" => 21,
        "title" => "Appartamento per Famiglie",
        "description" => "Ideale per famiglie, con ampi spazi e vicino a scuole e parchi.",
        "beds" => 4,
        "bathrooms" => 2,
        "rooms" => 5,
        "mq" => 150,
        "address" => "Via dei Bambini 7, Roma",
        "lat" => "41.93003",
        "long" => "12.45531",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-26.jpg"
    ],
    [
        "id" => 22,
        "title" => "Appartamento con Spa Privata",
        "description" => "Esclusivo appartamento con spa privata e zona benessere.",
        "beds" => 2,
        "bathrooms" => 2,
        "rooms" => 3,
        "mq" => 110,
        "address" => "Via delle Terme 18, Bologna",
        "lat" => "44.494887",
        "long" => "11.342616",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/rooftop%20terrace%20edit.jpg"
    ],
    [
        "id" => 23,
        "title" => "Appartamento con Giardino e Barbecue",
        "description" => "Spazioso appartamento con giardino privato e area barbecue, ideale per famiglie.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 110,
        "address" => "Via delle Palme 8, Catania",
        "lat" => "37.507876",
        "long" => "15.083560",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/pool%20w%20view%20edited.jpg"
    ],
    [
        "id" => 24,
        "title" => "Attico con Vista Panoramica",
        "description" => "Elegante attico con terrazza panoramica e vista mozzafiato sulla città.",
        "beds" => 2,
        "bathrooms" => 2,
        "rooms" => 3,
        "mq" => 95,
        "address" => "Via San Lorenzo 12, Torino",
        "lat" => "45.070312",
        "long" => "7.686856",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-3.jpg"
    ],
    [
        "id" => 25,
        "title" => "Appartamento Rustico in Montagna",
        "description" => "Accogliente appartamento in stile rustico, situato in montagna con vista sui panorami naturali.",
        "beds" => 4,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 120,
        "address" => "Strada delle Alpi 5, Cortina d'Ampezzo",
        "lat" => "46.540298",
        "long" => "12.119927",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-18.jpg"
    ],
    [
        "id" => 26,
        "title" => "Appartamento con Piscina e Giardino",
        "description" => "Lussuoso appartamento con piscina privata e giardino ben curato.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 140,
        "address" => "Via dei Fiori 22, Pisa",
        "lat" => "43.722839",
        "long" => "10.396595",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-19.jpg"
    ],
    [
        "id" => 27,
        "title" => "Monolocale con Arredamento Designer",
        "description" => "Moderno monolocale con arredamento di design e vista sulla città.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 45,
        "address" => "Via dei Designer 8, Milano",
        "lat" => "45.45471",
        "long" => "9.1325",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-10.jpg"
    ],
    [
        "id" => 28,
        "title" => "Appartamento con Terrazzo e Vista sulla Collina",
        "description" => "Elegante appartamento con ampio terrazzo e vista sulle colline circostanti.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 90,
        "address" => "Via delle Colline 10, Perugia",
        "lat" => "43.112423",
        "long" => "12.360827",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-9.jpg"
    ],
    [
        "id" => 29,
        "title" => "Appartamento con Garage e Cantina",
        "description" => "Appartamento spazioso con garage privato e cantina, situato in zona tranquilla.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 110,
        "address" => "Via del Garage 15, Bergamo",
        "lat" => "45.698350",
        "long" => "9.677268",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-8.jpg"
    ],
    [
        "id" => 30,
        "title" => "Appartamento con Sauna Privata",
        "description" => "Moderno appartamento con sauna privata e zona benessere, perfetto per rilassarsi.",
        "beds" => 2,
        "bathrooms" => 2,
        "rooms" => 3,
        "mq" => 100,
        "address" => "Via delle Terme 25, Bologna",
        "lat" => "44.494887",
        "long" => "11.342616",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-7.jpg"
    ],
    [
        "id" => 31,
        "title" => "Villa con Vista sul Mare",
        "description" => "Elegante villa con vista mozzafiato sul mare, dotata di ampio giardino e piscina.",
        "beds" => 5,
        "bathrooms" => 3,
        "rooms" => 6,
        "mq" => 250,
        "address" => "Via delle Onde 20, Rimini",
        "lat" => "44.067803",
        "long" => "12.568154",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-6.jpg"
    ],
    [
        "id" => 32,
        "title" => "Appartamento in Palazzo Storico",
        "description" => "Appartamento affascinante in un elegante palazzo storico, con dettagli d'epoca.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 120,
        "address" => "Via Storica 30, Firenze",
        "lat" => "43.769562",
        "long" => "11.255814",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-5.jpg"
    ],
    [
        "id" => 33,
        "title" => "Loft con Vista sul Fiume",
        "description" => "Moderno loft con ampie finestre e vista panoramica sul fiume.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 80,
        "address" => "Lungofiume 8, Torino",
        "lat" => "45.070312",
        "long" => "7.686856",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1200/s3/2/3585/web%20version-4.jpg"
    ],
    [
        "id" => 34,
        "title" => "Appartamento con Spa e Jacuzzi",
        "description" => "Appartamento esclusivo con spa privata e jacuzzi, per un soggiorno di lusso.",
        "beds" => 2,
        "bathrooms" => 2,
        "rooms" => 3,
        "mq" => 110,
        "address" => "Via della Spa 15, Roma",
        "lat" => "41.93003",
        "long" => "12.45531",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-8.jpg"
    ],
    [
        "id" => 35,
        "title" => "Attico con Terrazza e Vista sul Mare",
        "description" => "Elegante attico con grande terrazza e vista spettacolare sul mare.",
        "beds" => 4,
        "bathrooms" => 3,
        "rooms" => 5,
        "mq" => 150,
        "address" => "Lungomare 30, Salerno",
        "lat" => "40.682708",
        "long" => "14.765142",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-7.jpg"
    ],
    [
        "id" => 36,
        "title" => "Monolocale con Terrazzo",
        "description" => "Accogliente monolocale con ampio terrazzo, perfetto per il relax.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 50,
        "address" => "Via del Sole 15, Genova",
        "lat" => "44.405650",
        "long" => "8.946256",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-6.jpg"
    ],
    [
        "id" => 37,
        "title" => "Appartamento con Vista sulla Collina",
        "description" => "Elegante appartamento con vista panoramica sulle colline circostanti.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 120,
        "address" => "Via delle Colline 25, Bologna",
        "lat" => "44.494887",
        "long" => "11.342616",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-5.jpg"
    ],
    [
        "id" => 38,
        "title" => "Villa con Piscina e Giardino",
        "description" => "Splendida villa con piscina privata e giardino ben curato.",
        "beds" => 6,
        "bathrooms" => 4,
        "rooms" => 8,
        "mq" => 300,
        "address" => "Via delle Rose 12, Rimini",
        "lat" => "44.067803",
        "long" => "12.568154",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-9.jpg"
    ],
    [
        "id" => 39,
        "title" => "Appartamento con Balcone e Vista Mare",
        "description" => "Accogliente appartamento con balcone e vista mozzafiato sul mare.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 70,
        "address" => "Via del Mare 10, Amalfi",
        "lat" => "40.633",
        "long" => "14.602",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-10.jpg"
    ],
    [
        "id" => 40,
        "title" => "Casa Vacanze con Giardino e Vista Lago",
        "description" => "Casa vacanze con giardino privato e splendida vista sul lago.",
        "beds" => 4,
        "bathrooms" => 2,
        "rooms" => 5,
        "mq" => 150,
        "address" => "Via del Lago 8, Como",
        "lat" => "45.808059",
        "long" => "9.085176",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-11.jpg"
    ],
    [
        "id" => 41,
        "title" => "Attico con Terrazza e Vista sulla Città",
        "description" => "Attico elegante con grande terrazza e vista panoramica sulla città.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 130,
        "address" => "Piazza San Marco 5, Venezia",
        "lat" => "45.4345",
        "long" => "12.3584",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-13.jpg"
    ],
    [
        "id" => 42,
        "title" => "Appartamento con Giardino e Area Relax",
        "description" => "Appartamento spazioso con giardino privato e area relax all'aperto.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 110,
        "address" => "Via delle Palme 10, Catania",
        "lat" => "37.507876",
        "long" => "15.083560",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-12.jpg"
    ],
    [
        "id" => 43,
        "title" => "Appartamento con Sauna e Spa",
        "description" => "Elegante appartamento con sauna privata e zona spa per un relax totale.",
        "beds" => 2,
        "bathrooms" => 2,
        "rooms" => 3,
        "mq" => 100,
        "address" => "Via delle Terme 30, Bologna",
        "lat" => "44.494887",
        "long" => "11.342616",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-16.jpg"
    ],
    [
        "id" => 44,
        "title" => "Appartamento con Garage e Terrazzo",
        "description" => "Spazioso appartamento con garage privato e grande terrazzo per godersi l'esterno.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 120,
        "address" => "Via del Garage 10, Bergamo",
        "lat" => "45.698350",
        "long" => "9.677268",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-17.jpg"
    ],
    [
        "id" => 45,
        "title" => "Loft con Arredamento Moderno",
        "description" => "Moderno loft con arredamento elegante e ampie finestre.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 85,
        "address" => "Via dei Design 5, Milano",
        "lat" => "45.45471",
        "long" => "9.1325",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-19.jpg"
    ],
    [
        "id" => 46,
        "title" => "Appartamento in Zona Tranquilla",
        "description" => "Accogliente appartamento situato in una zona tranquilla e residenziale.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 80,
        "address" => "Via del Silenzio 7, Torino",
        "lat" => "45.070312",
        "long" => "7.686856",
        "image" => "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1110/s3/2/97682/9450-forest-springs-dr-dallas-tx-75243-high-res-20.jpg"
    ],
    [
        "id" => 47,
        "title" => "Villa con Giardino e Vista Mare",
        "description" => "Elegante villa con giardino privato e vista mozzafiato sul mare.",
        "beds" => 5,
        "bathrooms" => 3,
        "rooms" => 6,
        "mq" => 250,
        "address" => "Via del Mare 50, Cagliari",
        "lat" => "39.2238",
        "long" => "9.1216",
        "image" => "https://pnwapts.com/wp-content/uploads/2021/03/Link-14_2.jpg"
    ],
    [
        "id" => 48,
        "title" => "Appartamento con Vista sul Fiume",
        "description" => "Spazioso appartamento con vista panoramica sul fiume e arredi moderni.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 120,
        "address" => "Lungofiume 20, Torino",
        "lat" => "45.070312",
        "long" => "7.686856",
        "image" => "https://pnwapts.com/wp-content/uploads/2021/03/Link-14_3.jpg"
    ],
    [
        "id" => 49,
        "title" => "Monolocale con Giardino Privato",
        "description" => "Accogliente monolocale con giardino privato e spazi ben arredati.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 55,
        "address" => "Via del Giardino 9, Pisa",
        "lat" => "43.722839",
        "long" => "10.396593",
        "image" => "https://pnwapts.com/wp-content/uploads/2021/03/Link-14_4.jpg"
    ],
    [
        "id" => 50,
        "title" => "Appartamento con Balcone e Vista Montagna",
        "description" => "Spazioso appartamento con balcone e vista panoramica sulle montagne.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 3,
        "mq" => 80,
        "address" => "Via delle Montagne 25, Aosta",
        "lat" => "45.7373",
        "long" => "7.3206",
        "image" => "https://pnwapts.com/wp-content/uploads/2021/03/Link-14_5.jpg"
    ],
    [
        "id" => 51,
        "title" => "Attico con Terrazza e la Città",
        "description" => "Attico moderno con terrazza panoramica e vista spettacolare sulla città.",
        "beds" => 4,
        "bathrooms" => 3,
        "rooms" => 5,
        "mq" => 150,
        "address" => "Piazza della Libertà 10, Milano",
        "lat" => "45.45471",
        "long" => "9.1325",
        "image" => "https://pnwapts.com/wp-content/uploads/2021/03/Link-14_6.jpg"
    ],
    [
        "id" => 52,
        "title" => "Appartamento con Camere Ample e Luminoso",
        "description" => "Luminoso appartamento con camere ampie e ben arredate.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 120,
        "address" => "Via della Luce 30, Roma",
        "lat" => "41.93003",
        "long" => "12.45531",
        "image" => "https://pnwapts.com/wp-content/uploads/2021/03/Link-14_7.jpg"
    ],
    [
        "id" => 53,
        "title" => "Casa con Vista Panoramica e Piscina",
        "description" => "Casa elegante con vista panoramica e piscina privata.",
        "beds" => 5,
        "bathrooms" => 3,
        "rooms" => 6,
        "mq" => 200,
        "address" => "Via del Panorama 15, Napoli",
        "lat" => "40.8522",
        "long" => "14.2681",
        "image" => "https://pnwapts.com/wp-content/uploads/2021/03/Link-14_8.jpg"
    ],
    [
        "id" => 54,
        "title" => "Appartamento con Terrazzo e Spazi Aperti",
        "description" => "Spazioso appartamento con terrazzo privato e aree aperte per rilassarsi.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 130,
        "address" => "Via degli Spazi 12, Firenze",
        "lat" => "43.7696",
        "long" => "11.2558",
        "image" => "https://pnwapts.com/wp-content/uploads/2021/03/Link-14_9.jpg"
    ],
    [
        "id" => 55,
        "title" => "Monolocale con Cucina Completa e Balcone",
        "description" => "Monolocale ben arredato con cucina completa e balcone privato.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 60,
        "address" => "Via della Cucina 8, Verona",
        "lat" => "45.4384",
        "long" => "10.9916",
        "image" => "https://pnwapts.com/wp-content/uploads/2021/03/Link-14_10.jpg"
    ],
    [
        "id" => 56,
        "title" => "Appartamento con Terrazza e Vista Sul Giardino",
        "description" => "Accogliente appartamento con terrazza privata e vista sul giardino.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 70,
        "address" => "Via del Giardino 22, Siena",
        "lat" => "43.3188",
        "long" => "11.3308",
        "image" => "https://pnwapts.com/wp-content/uploads/2021/03/Link-14_11.jpg"
    ],
    [
        "id" => 57,
        "title" => "Villa con Ampio Parco e Piscina",
        "description" => "Elegante villa con ampio parco e piscina privata.",
        "beds" => 7,
        "bathrooms" => 4,
        "rooms" => 8,
        "mq" => 350,
        "address" => "Via del Parco 5, Pescara",
        "lat" => "42.4627",
        "long" => "14.2161",
        "image" => "https://resource.rentcafe.com/image/upload/x_0,y_0,w_1461,h_900,c_crop/q_auto,f_auto,c_limit,w_1440/s3/2/3585/deskins1_linkbroad_photofrommint(1).png"
    ],
    [
        "id" => 58,
        "title" => "Appartamento con Vista e Accesso alla Spiaggia",
        "description" => "Spazioso appartamento con vista mare e accesso diretto alla spiaggia.",
        "beds" => 4,
        "bathrooms" => 2,
        "rooms" => 5,
        "mq" => 140,
        "address" => "Lungomare 50, Rimini",
        "lat" => "44.0678",
        "long" => "12.5682",
        "image" => "https://resource.rentcafe.com/image/upload/x_0,y_0,w_1980,h_1321,c_crop/q_auto,f_auto,c_limit,w_1440/s3/2/3585/a1%20living%20room(1).jpg"
    ],
    [
        "id" => 59,
        "title" => "Attico con Terrazza e Vista sui Monti",
        "description" => "Moderno attico con terrazza e vista spettacolare sulle montagne.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 130,
        "address" => "Via dei Monti 10, Trento",
        "lat" => "46.0670",
        "long" => "11.1217",
        "image" => "https://static.dezeen.com/uploads/2022/08/gheorghe-puzzle-link-apartment-vienna-interiors_dezeen_2364_col_hero.jpg"
    ],
    [
        "id" => 60,
        "title" => "Appartamento con Giardino e Accesso Privato",
        "description" => "Elegante appartamento con giardino privato e accesso diretto alla zona verde.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 75,
        "address" => "Via del Verde 8, Bologna",
        "lat" => "44.4949",
        "long" => "11.3426",
        "image" => "https://interiorlover.in/wp-content/uploads/2021/04/Tanuja-Rana-Associates-9-800x534.jpg"
    ],
    [
        "id" => 61,
        "title" => "Loft con Arredi Vintage e Vista Urbana",
        "description" => "Loft unico con arredi vintage e vista panoramica sulla città.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 90,
        "address" => "Via degli Artisti 3, Milano",
        "lat" => "45.45471",
        "long" => "9.1325",
        "image" => "https://interiorlover.in/wp-content/uploads/2021/04/Tanuja-Rana-Associates-10-800x527.jpg"
    ],
    [
        "id" => 62,
        "title" => "Appartamento in Centro con Terrazza",
        "description" => "Elegante appartamento in centro città con terrazza privata.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 75,
        "address" => "Piazza della Repubblica 4, Firenze",
        "lat" => "43.7696",
        "long" => "11.2558",
        "image" => "https://interiorlover.in/wp-content/uploads/2021/04/Tanuja-Rana-Associates-11-800x527.jpg"
    ],
    [
        "id" => 63,
        "title" => "Monolocale con Arredi Moderni e Vista Mare",
        "description" => "Monolocale con arredi moderni e vista mozzafiato sul mare.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 50,
        "address" => "Via del Mare 10, Sorrento",
        "lat" => "40.6217",
        "long" => "14.3755",
        "image" => "https://interiorlover.in/wp-content/uploads/2021/04/Tanuja-Rana-Associates-6.jpg"
    ],
    [
        "id" => 64,
        "title" => "Casa di Campagna con Giardino e Fattoria",
        "description" => "Incantevole casa di campagna con ampio giardino e fattoria privata.",
        "beds" => 6,
        "bathrooms" => 4,
        "rooms" => 7,
        "mq" => 200,
        "address" => "Via della Fattoria 8, Siena",
        "lat" => "43.3188",
        "long" => "11.3308",
        "image" => "https://media.istockphoto.com/id/1018717866/it/foto/una-delle-strade-di-milano.jpg?s=1024x1024&w=is&k=20&c=lzA5m47NxUVQ6ScwZ32YPaydiDSQHPr6d__1kU70JPc="
    ],
    [
        "id" => 65,
        "title" => "Appartamento con Area Fitness e Spa",
        "description" => "Moderno appartamento con area fitness e spa privata.",
        "beds" => 2,
        "bathrooms" => 2,
        "rooms" => 3,
        "mq" => 100,
        "address" => "Via del Benessere 12, Bologna",
        "lat" => "44.4949",
        "long" => "11.3426",
        "image" => "https://media.istockphoto.com/id/1355222547/it/foto/architettura-del-novecento-a-milano.jpg?s=1024x1024&w=is&k=20&c=r1Y6gnp_y4MVjYSvx10C64Sw68_ZntZfzmu4P6OnUP4="
    ],
    [
        "id" => 66,
        "title" => "Attico con Panoramica sul Parco",
        "description" => "Lussuoso attico con terrazza e vista panoramica su un grande parco.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 140,
        "address" => "Piazza del Parco 5, Torino",
        "lat" => "45.0703",
        "long" => "7.6869",
        "image" => "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/05/e2/1e/luna-muna.jpg?w=1200&h=-1&s=1"
    ],
    [
        "id" => 67,
        "title" => "Villa in Collina con Vista e Piscina",
        "description" => "Elegante villa situata in collina con vista panoramica e piscina.",
        "beds" => 5,
        "bathrooms" => 3,
        "rooms" => 6,
        "mq" => 250,
        "address" => "Via della Collina 20, Lucca",
        "lat" => "43.8514",
        "long" => "10.5110",
        "image" => "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/37/63/27/habitacion-doble.jpg?w=1200&h=-1&s=1"
    ],
    [
        "id" => 68,
        "title" => "Appartamento con Terrazza e Vista su Palazzo",
        "description" => "Appartamento con una terrazza privata e vista su un palazzo storico in Napoli.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 80,
        "address" => "Piazza Storica 15, Napoli",
        "lat" => "40.8522",
        "long" => "14.2681",
        "image" => "https://www.kireti.it/wp-content/uploads/2021/04/iStock-1225226886-scaled.jpg"
    ],
    [
        "id" => 69,
        "title" => "Loft con Spazi Aperti e Design Contemporaneo",
        "description" => "Loft con spazi aperti e design contemporaneo, ideale per famiglie.",
        "beds" => 4,
        "bathrooms" => 2,
        "rooms" => 3,
        "mq" => 120,
        "address" => "Via del Design 7, Torino",
        "lat" => "45.0703",
        "long" => "7.6869",
        "image" => "https://www.mansarda.it/wp-content/uploads/2024/09/salotto-768x518.jpg"
    ],
    [
        "id" => 70,
        "title" => "Appartamento con Giardino e Cucina all'Aperto",
        "description" => "Spazioso appartamento con giardino privato e cucina all'aperto.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 110,
        "address" => "Via del Giardino 14, Verona",
        "lat" => "45.4384",
        "long" => "10.9916",
        "image" => "https://www.mansarda.it/wp-content/uploads/2024/09/luce-specchio-768x512.png"
    ],
    [
        "id" => 71,
        "title" => "Villa con Terrazza e Vista sul Lago",
        "description" => "Elegante villa con terrazza e vista panoramica sul lago.",
        "beds" => 6,
        "bathrooms" => 4,
        "rooms" => 7,
        "mq" => 300,
        "address" => "Via del Lago 7, Como",
        "lat" => "45.8081",
        "long" => "9.0852",
        "image" => "https://www.mansarda.it/wp-content/uploads/2024/09/letto-sotto-finestra-1280x864.jpg"
    ],
    [
        "id" => 72,
        "title" => "Appartamento con Terrazza e Vista sui Tetti",
        "description" => "Appartamento con grande terrazza e vista sui tetti della città.",
        "beds" => 2,
        "bathrooms" => 1,
        "rooms" => 2,
        "mq" => 70,
        "address" => "Via dei Tetti 12, Roma",
        "lat" => "41.93003",
        "long" => "12.45531",
        "image" => "https://www.mansarda.it/wp-content/uploads/2024/09/sala-giochi-1280x960.jpg"
    ],
    [
        "id" => 73,
        "title" => "Casa con Patio e Vista sul Mare",
        "description" => "Casa con patio esterno e vista spettacolare sul mare.",
        "beds" => 5,
        "bathrooms" => 3,
        "rooms" => 6,
        "mq" => 220,
        "address" => "Via del Mare 33, Catania",
        "lat" => "37.5079",
        "long" => "15.0836",
        "image" => "https://www.fundar.com.ar/resources/original/productos/frida/renders/015.jpg"
    ],
    [
        "id" => 74,
        "title" => "Monolocale con Arredi Eleganti e Vista Città",
        "description" => "Monolocale elegante con vista mozzafiato sulla città.",
        "beds" => 1,
        "bathrooms" => 1,
        "rooms" => 1,
        "mq" => 55,
        "address" => "Via dell'Eleganza 9, Milano",
        "lat" => "45.45471",
        "long" => "9.1325",
        "image" => "https://www.joyjar.it/wp-content/uploads/2018/03/real-estate-3297625_1920-min.jpg"
    ],
    [
        "id" => 75,
        "title" => "Appartamento con Sala Cinema e Jacuzzi",
        "description" => "Moderno appartamento con sala cinema privata e jacuzzi.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 130,
        "address" => "Via del Cinema 8, Bologna",
        "lat" => "44.4949",
        "long" => "11.3426",
        "image" => "https://www.fundar.com.ar/resources/original/productos/frida/renders/005.jpg"
    ],
    [
        "id" => 76,
        "title" => "Terrazza e Vista sul Mare",
        "description" => "Elegante attico con terrazza e vista panoramica sul mare.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 150,
        "address" => "Lungomare 12, Genova",
        "lat" => "44.4056",
        "long" => "8.9462",
        "image" => "https://www.fundar.com.ar/resources/original/productos/frida/renders/009.jpg"
    ],
    [
        "id" => 77,
        "title" => "Appartamento con Giardino e Spa Privata",
        "description" => "Appartamento con giardino privato e zona spa esclusiva.",
        "beds" => 2,
        "bathrooms" => 2,
        "rooms" => 3,
        "mq" => 85,
        "address" => "Via del Relax 6, Torino",
        "lat" => "45.0703",
        "long" => "7.6869",
        "image" => "https://www.fundar.com.ar/resources/original/productos/frida/renders/010.jpg"
    ],
    [
        "id" => 78,
        "title" => "Villa con Vigneti e Piscina",
        "description" => "Affascinante villa con vista sui vigneti e piscina privata.",
        "beds" => 6,
        "bathrooms" => 4,
        "rooms" => 7,
        "mq" => 280,
        "address" => "Via dei Vigneti 18, Chianti",
        "lat" => "43.5800",
        "long" => "11.3045",
        "image" => "https://www.fundar.com.ar/resources/original/productos/frida/renders/011.jpg"
    ],
    [
        "id" => 79,
        "title" => "Appartamento con Vista Panoramica e Terrazza",
        "description" => "Spazioso appartamento con terrazza privata e vista panoramica.",
        "beds" => 3,
        "bathrooms" => 2,
        "rooms" => 4,
        "mq" => 120,
        "address" => "Piazza Panorama 7, Verona",
        "lat" => "45.4384",
        "long" => "10.9916",
        "image" => "https://www.fundar.com.ar/resources/original/productos/frida/renders/012.jpg"
    ],
    [
        "id" => 80,
        "title" => "Casa con Accesso Privato al Lago",
        "description" => "Casa con accesso diretto al lago e ampio spazio esterno.",
        "beds" => 4,
        "bathrooms" => 3,
        "rooms" => 5,
        "mq" => 180,
        "address" => "Via del Lago 22, Como",
        "lat" => "45.8081",
        "long" => "9.0852",
        "image" => "https://cf.bstatic.com/xdata/images/hotel/max1024x768/290018095.jpg?k=dc32085f610e7b5491cf26b5e23d854996568a7e115524a569bdbdc2743e4463&o=&hp=1"
    ],
];
